kind: pipeline
name: default

steps:
  - name: build
    image: docker/compose:1.29.2
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker-compose down --rmi all && docker-compose build --no-cache && docker-compose up -d

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
